site_name: swarmcli-cd
docs_dir: docs
repo_url: https://github.com/Eldara-Tech/swarmcli-cd
repo_name: Eldara-Tech/swarmcli-cd
theme:
  name: mkdocs
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration: configuration.md
  - Concepts: concepts.md
  - HTTP API: api.md
  - Web UI: web-ui.md
  - Extensibility: extensibility.md
markdown_extensions:
  - toc:
      permalink: true
