// SPDX-License-Identifier: Apache-2.0
// Copyright © 2026 Eldara Tech

// The types in src/api/types.ts against documents the Go types actually
// produced.
//
// The fixtures beside this file are generated by application/fixtures_test.go,
// which marshals a fully-populated and a zero value of every document the API
// serves and fails when the committed JSON drifts. So the two halves catch
// different things: a field added or retagged in Go fails that test until the
// fixtures are regenerated, and a regenerated fixture that this file's types no
// longer describe fails `npm run typecheck`.
//
// **Most of this test does not run.** The assignments below are checked by tsc
// and erased, and that is deliberate: optionality has no runtime representation,
// so the only place `revisions?: Revision[]` can be proved wrong by a document
// that omits nothing is the compiler. The expectations at the bottom are the
// three findings worth stating out loud to a reader as well as to a compiler.

import { describe, expect, it } from 'vitest'

import { zeroTimestamp, type ControllerStatus, type DiffResponse, type History, type View } from '../api/types'

import controllerStatusFull from './fixtures/controller-status-full.json'
import controllerStatusZero from './fixtures/controller-status-zero.json'
import diffConverged from './fixtures/diff-converged.json'
import diffFull from './fixtures/diff-full.json'
import diffNotPlanned from './fixtures/diff-not-planned.json'
import historyFull from './fixtures/history-full.json'
import historyNeverDeployed from './fixtures/history-never-deployed.json'
import historyZero from './fixtures/history-zero.json'
import viewFull from './fixtures/view-full.json'
import viewZero from './fixtures/view-zero.json'

/**
 * Loose widens every string-literal union in T to `string`, recursively.
 *
 * It exists because TypeScript infers a JSON module's every string as `string`,
 * so `viewFull.status.sync.state` is not assignable to SyncState however
 * correct it is. Widening only the leaves keeps the one property this check is
 * for: a homomorphic mapped type preserves `?`, so assigning a fixture to
 * Loose<T> still fails when the document omits a key T declares required, or
 * carries null where T does not permit it.
 *
 * What it cannot catch is the other direction — a key the document has and T
 * does not — because excess-property checking applies only to fresh object
 * literals. That direction is caught in Go instead: a new field changes the
 * committed fixture, and the fixture test fails until somebody regenerates it
 * and sees the new key in the diff.
 */
type Loose<T> = T extends string
  ? string
  : T extends (infer E)[]
    ? Loose<E>[]
    : T extends object
      ? { [K in keyof T]: Loose<T[K]> }
      : T

// Every fixture, assigned to the type it is meant to be. A failure here is a
// type in src/api/types.ts that does not describe what the controller sends.
const _viewFull: Loose<View> = viewFull
const _viewZero: Loose<View> = viewZero
const _statusFull: Loose<ControllerStatus> = controllerStatusFull
const _statusZero: Loose<ControllerStatus> = controllerStatusZero
const _historyFull: Loose<History> = historyFull
const _historyZero: Loose<History> = historyZero
const _historyNeverDeployed: Loose<History> = historyNeverDeployed
const _diffFull: Loose<DiffResponse> = diffFull
const _diffConverged: Loose<DiffResponse> = diffConverged
const _diffNotPlanned: Loose<DiffResponse> = diffNotPlanned

// noUnusedLocals is on, and these are deliberately unused: their whole job is to
// be checked. Referencing them once is cheaper than an exemption that would also
// stop catching a genuinely dead binding.
void [
  _viewFull,
  _viewZero,
  _statusFull,
  _statusZero,
  _historyFull,
  _historyZero,
  _historyNeverDeployed,
  _diffFull,
  _diffConverged,
  _diffNotPlanned,
]

describe('the three shapes a UI written from the docs would get wrong', () => {
  it('reads a converged diff as null releases and an unplanned one as an empty list', () => {
    // Backwards from the guess: null is the success case.
    expect(diffConverged.releases).toBeNull()
    expect(diffConverged.planned).toBe(true)
    expect(diffNotPlanned.releases).toEqual([])
    expect(diffNotPlanned.planned).toBe(false)
  })

  it('reads a declared-but-never-deployed release as null revisions', () => {
    // The most likely runtime crash in Phase B: .map() on this throws.
    expect(historyNeverDeployed.releases[0].revisions).toBeNull()
    expect(historyZero.releases).toBeNull()
  })

  it('reads a never-loaded app set as the zero time, which parses as a number', () => {
    expect(controllerStatusZero.appSet.loadedAt).toBe(zeroTimestamp)
    // The trap: the usual "is this a real date" guard passes. Date.parse of the
    // zero time is a large negative number, not NaN, so a screen checking for
    // NaN renders the year 1 rather than "never".
    expect(Number.isNaN(Date.parse(zeroTimestamp))).toBe(false)
    expect(Date.parse(zeroTimestamp)).toBeLessThan(0)
  })

  it('never sends an empty enum, because the Go zero member marshals as "unknown"', () => {
    expect(viewZero.status.sync.state).toBe('unknown')
    expect(viewZero.status.health.state).toBe('unknown')
    expect(viewZero.spec.driftDetection).toBe('unknown')
  })

  it('omits a status field rather than sending it null', () => {
    // omitempty drops the key; it never produces null. That is what makes
    // `foo?: T` the right mirror for it, and `T | null` wrong.
    expect('drift' in viewZero.status).toBe(false)
    expect('releases' in viewZero.status).toBe(false)
    expect('lastSync' in viewZero.status.sync).toBe(false)
    expect(viewFull.status.drift).not.toBeUndefined()
  })
})
